#!/bin/bash
# Post-build script to generate index.html for static deployments

CLIENT_DIR="dist/client"

# Find the actual app entry chunk generated by Vite/TanStack.
# Avoid picking lazy-loaded chunks such as WebGISProject-*.js.
MAIN_JS=$(find "$CLIENT_DIR/assets" -maxdepth 1 -name 'index-*.js' | sort | tail -1)
CSS_FILES=$(ls "$CLIENT_DIR/assets"/*.css 2>/dev/null | sed 's|.*/||' | head -2 | xargs)

# Extract just the filenames
MAIN_JS_NAME=$(basename "$MAIN_JS")
CSS_LINKS=$(ls "$CLIENT_DIR/assets"/*.css 2>/dev/null | xargs -I {} basename {} | sed 's|^|    <link rel="stylesheet" href="/assets/|' | sed 's|$|" />|')

# Create index.html with dynamic asset references
cat > "$CLIENT_DIR/index.html" << EOF
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Spatial Storyteller Portfolio</title>
$CSS_LINKS
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/assets/$MAIN_JS_NAME"></script>
  </body>
</html>
EOF

echo "Generated $CLIENT_DIR/index.html for deployment"
echo "Main JS: $MAIN_JS_NAME"

# Use the prerendered TanStack shell as the deployment root. This keeps the
# bootstrap data that the client router expects during hydration.
if [ -f "$CLIENT_DIR/_shell.html" ]; then
  cp "$CLIENT_DIR/_shell.html" "$CLIENT_DIR/index.html"
fi
